image: node:lts

# allow caching for faster deployment
cache:
  paths:
    - node_modules/
    - public/
    - .cache/

pages:
  stage: deploy
  script:
    - npm install
    - npm run build:gitlab
  artifacts:
      paths:
        - public
  only:
    - main